name: nebby
channels:
  - conda-forge
dependencies:
  - python=3.13.11
  # general deps
  - zlib # pillow
  - jpeg # pillow
  - libpcap # naabu on linux
  # golang deps
  - conda-forge::go
  - conda-forge::go-cgo
  # rust deps
  - rust
  # python dev libraries
  - click
  # devops
  - git
  - uv
